# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: User

# Model Form Field configuration
form: $/sublimearts/sublimestripe/models/user/fields.yaml

# Model Class name
modelClass: SublimeArts\SublimeStripe\Models\User

# Default redirect location
defaultRedirect: sublimearts/sublimestripe/users

# Create page
create:
    title: Create User
    redirect: sublimearts/sublimestripe/users/update/:id
    redirectClose: sublimearts/sublimestripe/users

# Update page
update:
    title: Edit User
    redirect: sublimearts/sublimestripe/users
    redirectClose: sublimearts/sublimestripe/users

# Preview page
preview:
    title: Preview User